services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD
    volumes:
      - jenkins-vol:/var/jenkins_home
    ports:
      - 8080:8080

# reuse same volume on restart
volumes:
  jenkins-vol: