services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PASSWORD
        - VERSION
        - CHANGESET
    restart: unless-stopped
    volumes:
      - jenkins-vol:/var/jenkins_home
    ports:
      - 8080:8080

# reuse same volume on restart
volumes:
  jenkins-vol:
